### ISSUE TITLE
Tracking cost in two places

### ISSUE THREAD

**Issue by rthallisey** [fusor/apb-examples#103]
I don't think it make sense for us to track cost in two places. Instead, what if we don't track cost unless it's something other than free? That would have the potential to remove two options from all our spec files.

```yaml
    free: true
    ...
      cost: $0.00
```
